Server:
  Port: 5005
  RunMode: debug
Logger:
  FilePath: ../logs/logs.log
  Encoding: json
  Level: debug
Cors:
  AllowOrigins: "*"
Postgres:
  Host: postgres
  Port: 5432
  User: postgres
  Password: admin
  DbName: car_sale_db
  SslMode: false
redis:
  Host: redis
  Port: 6379
  Password: password
  Db: 0
  MinIdleConnections: 100
  PoolSize: 5000
  poolTimeout: 240